spring:
  application:
    name: redis

redis:
  host: localhost
  port: 6379
  chapters:
    chapter01:
      enabled: false
      type: lettuce # lettuce or jedis
    chapter02:
      enabled: true
      type: lettuce # lettuce or jedis

server:
  port: 9001